name: DepText Bloom

on:
  pull_request:
    branches: [main]
    paths:
      - '**/seed.nix'

permissions:
  contents: write

jobs:
  bloom:
    runs-on: ubuntu-latest
    steps:
      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # Only you can connect
      - uses: deptext/core@main
