name: DepText Bloom

on:
  pull_request:
    branches: [main]
    paths:
      - '**/seed.nix'

permissions:
  contents: write    # for pushing commits
  statuses: write    # for reporting status via API

jobs:
  bloom:
    runs-on: ubuntu-latest
    steps:
      - uses: deptext/core@main
